### ISSUE TITLE
Errors in SCNet.py

### ISSUE THREAD

**Issue by minygd** [backseason/SCNet#1]
Hello, there is a small bug in `SCNet.py`. 
In [Downloading URLs](https://github.com/backseason/SCNet/blob/master/scnet.py#L11), the 'scnet50' link is provided as 'scnet101'. It's a small mistake, since I can't access the AliYunCS due to the Permission Deny, I hope you can fix this.
And by the way, would 'scnet154' pretrained model be available in up-coming days?

**Comment by backseason** [comment]
Thank you for pointing out the mistake, and the link for scnet-50 has been updated.

For whether providing the scnet-154 model, it is still under consideration.

**Comment by minygd** [comment]
Thanks, this issue will be closed.
