### ISSUE TITLE
How do other networks use SCConv convolution block?

### ISSUE THREAD

**Issue by HiDay1** [backseason/SCNet#3]
If I want to use it in other networks, such as VGG ,ALexNet，and so on, I just need to replace the standard convolution blocks with this SCConv module whether or not？

**Comment by backseason** [comment]
You should include the K1 path as well: https://github.com/MCG-NKU/SCNet/blob/c0b5bd6aa919c00afb5815b2810e645e6a4a5976/scnet.py#L78 .
Also, the BN layers should be removed accordingly.

**Comment by HiDay1** [comment]
The BN layers ?  removed？ 
Does it refer to the BN layer contained in K1,K2,K3,K4？
Do I just need to remove them？

**Comment by backseason** [comment]
Architectures like VGGs do not have BN layers.
For those models, you should remove all the BN layers.
